apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hp0ra56sg-go
  janus-idp.io/tekton: hp0ra56sg-go
  backstage.io/kubernetes-id: hp0ra56sg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hp0ra56sg-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
